### ISSUE TITLE
橡树树苗铁砧改名BUG

### ISSUE THREAD

**Issue by Illusionika** [ybw0014/ExoticGarden-CN#1]
卧槽，这里怎么有个活跃的汉化分支

我发现个BUG在原版那边提交了issues，但好像已经不活跃几个月了

就是原版的树苗，普通的那种，在铁砧改名之后可以在增强型合成台进阶合成异域花园的魔法树苗

打个比方就是，你拿一个树苗在铁砧里改名成"煤炭植物" 然后把这个 "煤炭植物"放在增强型合成台里完美替代真正的煤炭植物来合成铁锭植物

以此类推，能跳过套娃直接白嫖任意魔法树苗

这个BUG应该给魔法树苗在合成的时候加个NBT检测能解决了吧

**Comment by ybw0014** [comment]
关闭的issue突然攻击我（
