### ISSUE TITLE
世界中的所有植物变为头

### ISSUE THREAD

**Issue by DenNotFound** [ybw0014/ExoticGarden-CN#12]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [ ] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/ExoticGarden/issues)，且没有找到相同的问题

### 问题描述

世界中的异域花园植物全部变为头

### 复现步骤

1. 新建一个世界（paper1.19）
2. 变头

### 预期行为

不是头。。。

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![image](https://user-images.githubusercontent.com/103357331/178137737-e91d9d39-1f02-460e-a0ee-c2797bed1fed.png)

### 插件版本

10

**Comment by ybw0014** [comment]
提供一下新建世界的方式

**Comment by DenNotFound** [comment]
> 提供一下新建世界的方式

/mv load
