### ISSUE TITLE
植物用骨粉催熟会一直往下破坏方块

### ISSUE THREAD

**Issue by DongShaoNB** [ybw0014/ExoticGarden-CN#13]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [x] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [x] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/ExoticGarden/issues)，且没有找到相同的问题

### 问题描述

视频演示链接 : https://www.bilibili.com/video/BV1aF411P7Lo
（有时会一直往下直到破坏了基岩后）

除视频中出现的植物一直往下外，还发现，植物走（下）过的格子用方块堵上会又一次掉落魔法精华

且原来种植过异域花园的格子再次种植异域花园植物时无法用骨粉催熟（那个格子首次种植时是可以催熟的）

### 复现步骤

视频演示链接 : https://www.bilibili.com/video/BV1aF411P7Lo

### 预期行为

植物不会往下破坏方块，种植过的格子后续种植异域花园植物仍可用骨粉催熟

（Minecraft版本用的是1.19，下面没得选）

### 服务端软件

Purpur

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

2022.07 正式版
![image](https://user-images.githubusercontent.com/54093566/181154793-de47f74f-6921-4c79-8da9-35fce1fbee1b.png)

### 插件版本

10

**Comment by ybw0014** [comment]
上游问题，等待修复：https://github.com/TheBusyBiscuit/ExoticGarden/issues/247

**Comment by AquawaNya** [comment]
甚至可以**破基岩**！！！！
问题很大，建议先增加检测基岩临时修复

**Comment by kelegele** [comment]
确实可以破坏基岩和地形

**Comment by ybw0014** [comment]
已确认为1.19特有的问题

**Comment by AquawaNya** [comment]
领地里可以破上面一格，如果吞箱子...

**Comment by AquawaNya** [comment]
> 已确认为1.19特有的问题

什么原因啊，我裂开，代码找了半天，而且代码没注释

**Comment by ybw0014** [comment]
尝试群内的测试版
