### ISSUE TITLE
bs 版本 异域花园使用error

### ISSUE THREAD

**Issue by shixinzia** [ybw0014/ExoticGarden-CN#23]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/ExoticGarden/issues)，且没有找到相同的问题

### 问题描述

使用时报错

### 复现步骤

无

### 预期行为

无报错

### 错误报告

https://paste.guizhanss.net/2LPsc

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

最新

### 插件版本

最新

**Comment by shixinzia** [comment]
https://paste.guizhanss.net/G1HpD 
新报错，不同event

**Comment by Aitchn** [comment]
我也是 似乎 沒有支援 v2023.06-release 互動類型的都會影響

**Comment by Xzavier0722** [comment]
本件属于粘液新版兼容性问题，后续请关注 #24
此外，本件中的异常在粘液内测版本中已添加兼容性接口，粘液科技赞助者可在频道内下载尝试。
