### ISSUE TITLE
食物完全無法合成

### ISSUE THREAD

**Issue by Aitchn** [ybw0014/ExoticGarden-CN#25]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/ExoticGarden/issues)，且没有找到相同的问题

### 问题描述

似乎所有的食物 都無法合成 似乎是 廚房 無法辨識
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/97263430/61d770f3-aad6-4933-9601-37369899e51f)

### 复现步骤

1. 建造好 廚房結構
2. 放置合成配方
3. 無法合成

### 预期行为

![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/97263430/5acfdb67-c81a-4387-8485-02d39722070d)
我想是 廚房無法辨識造成的 並不是只有一兩個 而是將近全部

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/97263430/0b783bcf-0ac9-4672-b8e6-dd6c167fc92e)

### 插件版本

1aa87ca

**Comment by StarWishsama** [comment]
复现不了🤔 测试合成的葡萄汁、草莓冰淇淋
是不是你摆错了，顺便要交互的是中间那个活版门

![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/25561848/d51dc7c1-72fd-44ec-8137-fbc49dc24590)

```
Slimefun 运行的服务器环境:
Paper git-Paper-69 (MC: 1.20.1)
Slimefun 5.0
Metrics-组件 #28
Java 17
```

**Comment by ybw0014** [comment]
stale
